### ISSUE TITLE
Talk

### ISSUE THREAD

**Issue by philipturner** [albanD/pytorch_dev_env_setup#1]

**Comment by albanD** [comment]
Hey @philipturner,
Sorry for the spotty communication :/ 
I think discussing this on slack is going to be the best way to go indeed. I just sent an invitation to the email on your github account, feel free to request to join with another one if you prefer as well.

**Comment by philipturner** [comment]
I don't have slack set up yet, and it hasn't appeared in my inbox yet. I'll look more into slack later today and try setting it up.

**Comment by philipturner** [comment]
@albanD I signed into slack but it's telling me to create a workspace instead of letting me manage a personal account. Could you send me your invitation again?

**Comment by albanD** [comment]
yes, i need an admin to confirm the request. You should get it shortly.

**Comment by philipturner** [comment]
Will I receive an email when the notification is approved?

**Comment by albanD** [comment]
Yes.
If you don't want to use the email from your github, you can request to join at pytorch.slack.com

**Comment by philipturner** [comment]
I still haven’t received the email. Are you able to contact the admin and ensure the invitation was sent?

**Comment by philipturner** [comment]
I got the invite!
